const data = {
  title: "232 Stays in Melbourne",
  desc: "Book your next stay in one of our properties",
  apartments: [
    {
      highlight: "Entire apartment rental in Collingwood",
      title: "A stylish Apt, 5 min walk to queen victoria market",
      rating: 4.9,
      location: "Collingwood VC",
      bed: 1,
      wifi: true,
      price: "$540 AUD Total",
      reviews: "202",
      rare: true,
    },
    {
      highlight: "Luxury Loft in CBD",
      title: "Modern Loft with Skyline Views",
      rating: 4.8,
      location: "Melbourne CBD",
      bed: 2,
      wifi: true,
      price: "$700 AUD Total",
      reviews: "150",
    },
    {
      highlight: "Charming Studio near the Beach",
      title: "Cozy Studio with Ocean Breeze",
      rating: 4.7,
      location: "St Kilda",
      bed: 1,
      wifi: true,
      price: "$450 AUD Total",
      reviews: "120",
    },
    {
      highlight: "Spacious Penthouse with Rooftop Terrace",
      title: "Penthouse Retreat in Southbank",
      rating: 5.0,
      location: "Southbank",
      bed: 3,
      wifi: true,
      price: "$850 AUD Total",
      reviews: "250",
    },
    {
      highlight: "Historic Apartment in Fitzroy",
      title: "Vintage Charm with Modern Comforts",
      rating: 4.6,
      location: "Fitzroy",
      bed: 2,
      wifi: true,
      price: "$600 AUD Total",
      reviews: "180",
    },
    {
      highlight: "Family-Friendly Apartment in Carlton",
      title: "Kid-Friendly Oasis near Melbourne Zoo",
      rating: 4.5,
      location: "Carlton",
      bed: 3,
      wifi: true,
      price: "$680 AUD Total",
      reviews: "200",
    },
  ],
};

export default data;
